const products = [
  // --- BURGER 180G ---
  { id: 1, name: "Cheese Burguer", description: "Pão brioche, burguer 180g, queijo prato duplo e maionese da casa", price: 31.70, category: "burger_180g", image: "images/products/burger_1.jpg", emoji: "🧀", rating: 4.9, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 2, name: "Salada Burguer", description: "Pão brioche, burguer 180g, queijo prato duplo, alface, tomate e maionese da casa", price: 32.90, category: "burger_180g", image: "images/products/burger_2.jpg", emoji: "🥗", rating: 4.8, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 3, name: "Pork Burguer", description: "Pão brioche, burguer de porco 180g, queijo prato, cream cheese, jalapeno, geleia de cebola, BBQ de goiaba e maionese da casa", price: 33.90, category: "burger_180g", image: "images/products/burger_3.jpg", emoji: "🐷", rating: 4.9, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 4, name: "Chicken House", description: "Pão brioche, frango empanado, queijo prato, catupiry, alface, tomate e maionese da casa", price: 39.20, category: "burger_180g", image: "images/products/burger_4.jpg", emoji: "🍗", rating: 4.8, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 5, name: "Texas Burguer", description: "Pão brioche, burguer 180g, queijo prato, bacon, geleia de cebola, picles de pepino e cebola, BBQ de goiaba e maionese da casa", price: 35.90, category: "burger_180g", image: "images/products/burger_5.jpg", emoji: "🔥", rating: 4.9, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 6, name: "Mexicano", description: "Pão brioche, burguer 180g, queijo prato, cream cheese, jalapeno, guacamole, doritos e BBQ de goiaba", price: 39.20, category: "burger_180g", image: "images/products/burger_6.jpg", emoji: "🌶️", rating: 4.7, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 7, name: "Mineiro", description: "Pão brioche, burguer 180g, queijo prato, queijo coalho, couve no alho e azeite, farofa de torresmos, BBQ de goiaba e maionese da casa", price: 40.30, category: "burger_180g", image: "images/products/burger_7.jpg", emoji: "🧂", rating: 4.9, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 8, name: "O Bravo", description: "Pão brioche, burguer de boi 180g, queijo prato, onions rings, duas fatias de bacon e maionese picante", price: 40.30, category: "burger_180g", image: "images/products/burger_8.jpg", emoji: "💪", rating: 4.9, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 9, name: "Monster Bacon", description: "Pão brioche, 2 burguers 180g, queijo prato duplo, muito bacon e maionese da casa", price: 58.30, category: "burger_180g", image: "images/products/burger_9.jpg", emoji: "👹", rating: 5.0, deliveryTime: "30-35 min", freeDelivery: true },
  { id: 10, name: "Bacon", description: "Pão brioche, burguer 180g, queijo prato, muito bacon e maionese da casa", price: 43.50, category: "burger_180g", image: "images/products/burger_10.jpg", emoji: "🥓", rating: 4.9, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 11, name: "Mega Cheese", description: "Pão brioche, burguer 180g, queijo prato, queijo coalho, requeijão cremoso, cheddar ou cream cheese e maionese da casa", price: 54.10, category: "burger_180g", image: "images/products/burger_11.jpg", emoji: "🧀", rating: 4.9, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 12, name: "Cheddar", description: "Pão brioche, burguer 180g, cheddar, geleia de cebola e bacon", price: 39.20, category: "burger_180g", image: "images/products/burger_12.jpg", emoji: "🟡", rating: 4.8, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 13, name: "Casal Perfeito", description: "Pão brioche, burguer de boi 180g, burguer de porco 180g, queijo prato, cream cheese, bacon, geleia de cebola, picles de pepino e cebola, BBQ de goiaba, mostarda com mel e maionese da casa", price: 58.30, category: "burger_180g", image: "images/products/burger_13.jpg", emoji: "👫", rating: 5.0, deliveryTime: "30-35 min", freeDelivery: true },
  { id: 14, name: "Egg Burguer", description: "Pão brioche, burguer de boi 180g, queijo prato, ovo, alface, tomate e maionese da casa", price: 39.20, category: "burger_180g", image: "images/products/burger_14.jpg", emoji: "🥚", rating: 4.8, deliveryTime: "25-30 min", freeDelivery: true },
  { id: 15, name: "Mega Monster", description: "Pão brioche, 3 burguers 180g, queijo prato triplo, muito bacon e maionese da casa", price: 68.90, category: "burger_180g", image: "images/products/burger_15.jpg", emoji: "👹", rating: 5.0, deliveryTime: "30-35 min", freeDelivery: true },
  { id: 16, name: "Pulled Pork", description: "Pão brioche, queijo prato e queijo coalho, copa lombo defumada, picles de pepino e cebola, BBQ de goiaba, mostarda com mel e maionese da casa", price: 39.20, category: "burger_180g", image: "images/products/burger_16.jpg", emoji: "🐷", rating: 4.9, deliveryTime: "25-30 min", freeDelivery: true },

  // --- BURGER 90G ---
  { id: 17, name: "Cheese Burguer 90g", description: "Pão brioche, burguer 90g, queijo prato e maionese da casa", price: 19.90, category: "burger_90g", image: "images/products/burger_17.jpg", emoji: "🧀", rating: 4.8, deliveryTime: "20-25 min", freeDelivery: true },
  { id: 18, name: "Salada Burguer 90g", description: "Pão brioche, burguer 90g, queijo prato, alface, tomate e maionese da casa", price: 21.90, category: "burger_90g", image: "images/products/burger_18.jpg", emoji: "🥗", rating: 4.7, deliveryTime: "20-25 min", freeDelivery: true },
  { id: 19, name: "Pork Burguer 90g", description: "Pão brioche, burguer de porco 90g, queijo prato, cream cheese, jalapeno e BBQ de goiaba", price: 22.90, category: "burger_90g", image: "images/products/burger_19.jpg", emoji: "🐷", rating: 4.8, deliveryTime: "20-25 min", freeDelivery: true },
  { id: 20, name: "Chicken 90g", description: "Pão brioche, frango empanado, queijo prato, catupiry e maionese", price: 24.20, category: "burger_90g", image: "images/products/burger_20.jpg", emoji: "🍗", rating: 4.7, deliveryTime: "20-25 min", freeDelivery: true },
  { id: 21, name: "Texas 90g", description: "Pão brioche, burguer 90g, queijo prato, bacon, geleia de cebola e BBQ de goiaba", price: 23.90, category: "burger_90g", image: "images/products/burger_21.jpg", emoji: "🔥", rating: 4.8, deliveryTime: "20-25 min", freeDelivery: true },
  { id: 22, name: "Mexicano 90g", description: "Pão brioche, burguer 90g, queijo prato, cream cheese, jalapeno, guacamole e doritos", price: 24.20, category: "burger_90g", image: "images/products/burger_22.jpg", emoji: "🌶️", rating: 4.6, deliveryTime: "20-25 min", freeDelivery: true },
  { id: 23, name: "Mineiro 90g", description: "Pão brioche, burguer 90g, queijo prato, queijo coalho e couve no alho", price: 25.30, category: "burger_90g", image: "images/products/burger_23.jpg", emoji: "🧂", rating: 4.8, deliveryTime: "20-25 min", freeDelivery: true },
  { id: 24, name: "Bravo 90g", description: "Pão brioche, burguer 90g, queijo prato, onions rings, bacon e maionese picante", price: 25.30, category: "burger_90g", image: "images/products/burger_24.jpg", emoji: "💪", rating: 4.7, deliveryTime: "20-25 min", freeDelivery: true },
  { id: 25, name: "Bacon 90g", description: "Pão brioche, burguer 90g, queijo prato, muito bacon e maionese", price: 26.50, category: "burger_90g", image: "images/products/burger_25.jpg", emoji: "🥓", rating: 4.8, deliveryTime: "20-25 min", freeDelivery: true },

  // --- HOT DOG ---
  { id: 26, name: "Hot Dog Simples", description: "Pão na chapa, cachorro-quente, maionese, mostarda e ketchup", price: 14.90, category: "hot_dog", image: "images/products/dog_1.jpg", emoji: "🌭", rating: 4.6, deliveryTime: "15-20 min", freeDelivery: true },
  { id: 27, name: "Hot Dog Completo", description: "Pão na chapa, cachorro-quente, batata palha, queijo, maionese, mostarda, ketchup e suco de cebola", price: 17.90, category: "hot_dog", image: "images/products/dog_2.jpg", emoji: "🌭", rating: 4.7, deliveryTime: "15-20 min", freeDelivery: true },

  // --- PORTIONS ---
  { id: 28, name: "Batata Fritas P", description: "Porção pequena de batata fritas crocantes", price: 12.90, category: "porcoes", image: "images/products/porcoes_1.jpg", emoji: "🍟", rating: 4.8, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 29, name: "Batata Fritas M", description: "Porção média de batata fritas crocantes", price: 17.90, category: "porcoes", image: "images/products/porcoes_2.jpg", emoji: "🍟", rating: 4.8, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 30, name: "Batata Fritas G", description: "Porção grande de batata fritas crocantes", price: 24.90, category: "porcoes", image: "images/products/porcoes_3.jpg", emoji: "🍟", rating: 4.9, deliveryTime: "15-20 min", freeDelivery: true },
  { id: 31, name: "Onion Rings P", description: "Porção pequena de cebola empanada e frita", price: 13.90, category: "porcoes", image: "images/products/porcoes_4.jpg", emoji: "🧅", rating: 4.7, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 32, name: "Onion Rings M", description: "Porção média de cebola empanada e frita", price: 18.90, category: "porcoes", image: "images/products/porcoes_5.jpg", emoji: "🧅", rating: 4.8, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 33, name: "Onion Rings G", description: "Porção grande de cebola empanada e frita", price: 25.90, category: "porcoes", image: "images/products/porcoes_6.jpg", emoji: "🧅", rating: 4.9, deliveryTime: "15-20 min", freeDelivery: true },
  { id: 34, name: "Nuggets", description: "10 unidades de frango empanado", price: 19.90, category: "porcoes", image: "images/products/porcoes_7.jpg", emoji: "🍗", rating: 4.7, deliveryTime: "15-20 min", freeDelivery: true },
  { id: 35, name: "Croqueta", description: "4 unidades de croqueta caseira", price: 12.90, category: "porcoes", image: "images/products/porcoes_8.jpg", emoji: "🥠", rating: 4.6, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 36, name: "Pastel de Queijo", description: "3 unidades de pastel de queijo frito", price: 14.90, category: "porcoes", image: "images/products/porcoes_9.jpg", emoji: "🧀", rating: 4.7, deliveryTime: "10-15 min", freeDelivery: true },

  // --- SAUCES ---
  { id: 37, name: "Molho Barbecue", description: "Pote com molho barbecue artesanal", price: 5.90, category: "molhos", image: "images/products/molhos_1.jpg", emoji: "🍯", rating: 4.8, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 38, name: "Molho Picante", description: "Pote com molho picante temperado", price: 5.90, category: "molhos", image: "images/products/molhos_2.jpg", emoji: "🌶️", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 39, name: "Maionese da Casa", description: "Pote com maionese especial Mr. Jaba", price: 5.90, category: "molhos", image: "images/products/molhos_3.jpg", emoji: "🤍", rating: 4.9, deliveryTime: "5-10 min", freeDelivery: false },

  // --- DESSERTS ---
  { id: 40, name: "Sorvete", description: "Pote de sorvete de baunilha com cobertura de chocolate", price: 12.90, category: "doces", image: "images/products/doces_1.jpg", emoji: "🍦", rating: 4.8, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 41, name: "Pudim", description: "Pudim de leite condensado com calda de caramelo", price: 11.90, category: "doces", image: "images/products/doces_2.jpg", emoji: "🍮", rating: 4.7, deliveryTime: "10-15 min", freeDelivery: true },

  // --- WATER/JUICE ---
  { id: 42, name: "Água 500ml", description: "Água mineral pura e refrescante", price: 3.50, category: "agua_suco", image: "images/products/bebidas_1.jpg", emoji: "💧", rating: 5.0, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 43, name: "Suco Natural Laranja", description: "Suco natural de laranja espremido na hora", price: 8.90, category: "agua_suco", image: "images/products/bebidas_2.jpg", emoji: "🍊", rating: 4.9, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 44, name: "Suco Natural Melancia", description: "Suco natural de melancia gelado", price: 8.90, category: "agua_suco", image: "images/products/bebidas_3.jpg", emoji: "🍉", rating: 4.8, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 45, name: "Suco Natural Uva", description: "Suco natural de uva roxa gelado", price: 8.90, category: "agua_suco", image: "images/products/bebidas_4.jpg", emoji: "🍇", rating: 4.7, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 46, name: "Suco Abacaxi com Gengibre", description: "Suco natural de abacaxi com gengibre refrescante", price: 9.90, category: "agua_suco", image: "images/products/bebidas_5.jpg", emoji: "🍍", rating: 4.8, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 47, name: "Limonada Gelada", description: "Limonada natural gelada preparada na hora", price: 7.90, category: "agua_suco", image: "images/products/bebidas_6.jpg", emoji: "🍋", rating: 4.9, deliveryTime: "10-15 min", freeDelivery: true },

  // --- SOFT DRINKS ---
  { id: 48, name: "Coca-Cola 350ml", description: "Refrigerante Coca-Cola gelado", price: 6.90, category: "refrigerante", image: "images/products/refrigerante_1.jpg", emoji: "🥤", rating: 4.9, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 49, name: "Guaraná 350ml", description: "Guaraná gelado e refrescante", price: 6.90, category: "refrigerante", image: "images/products/refrigerante_2.jpg", emoji: "🥤", rating: 4.8, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 50, name: "Fanta Laranja 350ml", description: "Fanta Laranja gelada", price: 6.90, category: "refrigerante", image: "images/products/refrigerante_3.jpg", emoji: "🟠", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 51, name: "Fanta Uva 350ml", description: "Fanta Uva gelada", price: 6.90, category: "refrigerante", image: "images/products/refrigerante_4.jpg", emoji: "🟣", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 52, name: "Sprite 350ml", description: "Sprite gelada e refrescante", price: 6.90, category: "refrigerante", image: "images/products/refrigerante_5.jpg", emoji: "🟢", rating: 4.8, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 53, name: "Coca-Cola 500ml", description: "Refrigerante Coca-Cola grande", price: 8.90, category: "refrigerante", image: "images/products/refrigerante_6.jpg", emoji: "🥤", rating: 4.9, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 54, name: "Guaraná 500ml", description: "Guaraná grande e gelado", price: 8.90, category: "refrigerante", image: "images/products/refrigerante_7.jpg", emoji: "🥤", rating: 4.8, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 55, name: "Fanta Laranja 500ml", description: "Fanta Laranja grande", price: 8.90, category: "refrigerante", image: "images/products/refrigerante_8.jpg", emoji: "🟠", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 56, name: "Fanta Uva 500ml", description: "Fanta Uva grande", price: 8.90, category: "refrigerante", image: "images/products/refrigerante_9.jpg", emoji: "🟣", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 57, name: "Sprite 500ml", description: "Sprite grande e refrescante", price: 8.90, category: "refrigerante", image: "images/products/refrigerante_10.jpg", emoji: "🟢", rating: 4.8, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 58, name: "Tônica Antártica", description: "Tônica Antártica gelada", price: 7.90, category: "refrigerante", image: "images/products/refrigerante_11.jpg", emoji: "🥤", rating: 4.6, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 59, name: "Água Tônica", description: "Água tônica premium", price: 7.90, category: "refrigerante", image: "images/products/refrigerante_12.jpg", emoji: "💧", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 60, name: "Gatorade Laranja", description: "Gatorade sabor laranja", price: 8.90, category: "refrigerante", image: "images/products/refrigerante_13.jpg", emoji: "🏃", rating: 4.6, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 61, name: "Gatorade Uva", description: "Gatorade sabor uva", price: 8.90, category: "refrigerante", image: "images/products/refrigerante_14.jpg", emoji: "🏃", rating: 4.6, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 62, name: "Energético Red Bull", description: "Red Bull Energy Drink", price: 15.90, category: "refrigerante", image: "images/products/refrigerante_15.jpg", emoji: "⚡", rating: 4.5, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 63, name: "Chá Gelado Limão", description: "Chá gelado sabor limão refrescante", price: 6.90, category: "refrigerante", image: "images/products/refrigerante_16.jpg", emoji: "🍋", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 64, name: "Chá Gelado Pêssego", description: "Chá gelado sabor pêssego", price: 6.90, category: "refrigerante", image: "images/products/refrigerante_17.jpg", emoji: "🍑", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 65, name: "Chá Gelado Morango", description: "Chá gelado sabor morango", price: 6.90, category: "refrigerante", image: "images/products/refrigerante_18.jpg", emoji: "🍓", rating: 4.6, deliveryTime: "5-10 min", freeDelivery: false },

  // --- BEER ---
  { id: 66, name: "Brahma 350ml", description: "Cerveja Brahma gelada", price: 11.90, category: "cerveja", image: "images/products/cerveja_1.jpg", emoji: "🍺", rating: 4.7, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 67, name: "Skol 350ml", description: "Cerveja Skol gelada", price: 11.90, category: "cerveja", image: "images/products/cerveja_2.jpg", emoji: "🍺", rating: 4.6, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 68, name: "Heineken 350ml", description: "Cerveja Heineken importada gelada", price: 14.90, category: "cerveja", image: "images/products/cerveja_3.jpg", emoji: "🍺", rating: 4.8, deliveryTime: "5-10 min", freeDelivery: false },
  { id: 69, name: "Stella Artois 350ml", description: "Cerveja Stella Artois premium", price: 16.90, category: "cerveja", image: "images/products/cerveja_4.jpg", emoji: "🍺", rating: 4.9, deliveryTime: "5-10 min", freeDelivery: false },

  // --- DRAFT BEER (CHOPP) ---
  { id: 70, name: "Chopp Brahma 300ml", description: "Chopp Brahma gelado e refrescante", price: 13.90, category: "chopp", image: "images/products/chopp_1.jpg", emoji: "🍻", rating: 4.8, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 71, name: "Chopp Brahma 500ml", description: "Chopp Brahma grande e gelado", price: 19.90, category: "chopp", image: "images/products/chopp_2.jpg", emoji: "🍻", rating: 4.8, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 72, name: "Chopp Skol 300ml", description: "Chopp Skol gelado", price: 13.90, category: "chopp", image: "images/products/chopp_3.jpg", emoji: "🍻", rating: 4.7, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 73, name: "Chopp Skol 500ml", description: "Chopp Skol grande", price: 19.90, category: "chopp", image: "images/products/chopp_4.jpg", emoji: "🍻", rating: 4.7, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 74, name: "Chopp Heineken 300ml", description: "Chopp Heineken importado gelado", price: 16.90, category: "chopp", image: "images/products/chopp_5.jpg", emoji: "🍻", rating: 4.9, deliveryTime: "10-15 min", freeDelivery: true },
  { id: 75, name: "Chopp Heineken 500ml", description: "Chopp Heineken grande", price: 22.90, category: "chopp", image: "images/products/chopp_6.jpg", emoji: "🍻", rating: 4.9, deliveryTime: "10-15 min", freeDelivery: true },
];
